// Configuration for YTPlayer
// Automatically Generated by PhantomBot Core at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "maxerbox";
var auth="yjqrVzJ1e3FmDazKMHWPNZzhTKJz4C";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
